1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code modules, offering reusable solutions for developers to streamline common tasks in their projects. These libraries provide a set of functions and methods, promoting code efficiency and collaboration within the Python community. Developers leverage Python libraries to access ready-made solutions, enabling them to focus on the unique aspects of their projects without reinventing the wheel. This fosters an efficient and collaborative coding environment, enhancing the overall development experience.

2. What is the difference between Numpy array and List?

NumPy arrays are homogeneous, meaning they require elements of the same type, ensuring efficiency in numerical computations. On the other hand, Python lists are heterogeneous, allowing a mix of different data types within the same list. This heterogeneity provides flexibility but can lead to some trade-off in terms of numerical performance. When choosing between NumPy arrays and Python lists, it's crucial to consider whether your task demands homogeneity for optimized numerical operations or if the flexibility of handling different data types heterogeneously is more important.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np

arr1=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("shape of array:",arr1.shape)
print("size of array:",arr1.size)
print("dimension of array:",arr1.ndim)

shape of array: (3, 4)
size of array: 12
dimension of array: 2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
arr2=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("First row of array:",arr2[[0]])

First row of array: [[1 2 3 4]]


5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

In [10]:
arr3=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Element at the third row and fourth colum:",arr3[2,3])

Element at the third row and fourth colum: 12


6. Write code to extract all odd-indexes elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [19]:
arr4=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Odd-indexes element:",arr4[0::2,:])

Odd-indexes element: [[ 1  2  3  4]
 [ 9 10 11 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [26]:
import random
arr5=np.random.rand(3,3)
print("Random 3X3 Matrix:",arr5)

Random 3X3 Matrix: [[0.13023224 0.63151856 0.59901451]
 [0.06643477 0.73516098 0.7576631 ]
 [0.27502648 0.19912053 0.6929439 ]]


8. Describe the difference between np.random.rand and np.random.randn?

The key difference is in the distribution of the generated values. rand produces values uniformly distributed between 0 and 1, while randn produces values from a standard normal distribution.

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [37]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Reshape the array to a 3D array
extended_array = original_array.reshape(3, 4, 1)

# Print the original and extended arrays
print("Original Array:")
print(original_array)

print("\nExtended Array (3D):")
print(extended_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Extended Array (3D):
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [39]:
arr7=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Transpose is:\n",arr7.T)

Transpose is:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1:

a.Index wise multiplication

In [42]:
matrix_A2=np.array( [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matrix_B2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

index_wise_mul=matrix_A2*matrix_B2
print("Index_wise Multiplication:\n",index_wise_mul)

Index_wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


b. Matrix multiplication


In [46]:
matrix_A2=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matrix_B2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

# Transpose matrix_B2 to make dimensions compatible
matrix_B2_transposed = np.transpose(matrix_B2)

# Matrix multiplication using numpy.dot
matrix_mul = np.dot(matrix_A2, matrix_B2_transposed)

# Print the result
print("Matrix Multiplication:")
print(matrix_mul)

Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


c. Add both the matrices

In [48]:
matrix_A2=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matrix_B2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

matrix_sum=np.add(matrix_A2,matrix_B2)
print("Added Matrix:\n",matrix_sum)

Added Matrix:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


d.Subtract matrix B from A

In [49]:
# Element-wise subtraction using the - operator
matrix_difference = matrix_B2 - matrix_A2

# Print the result
print("Matrix Subtraction:")
print(matrix_difference)

Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


e.Divide Matrix B by A

In [50]:
# Element-wise division using the / operator
matrix_quotient = matrix_B2 / matrix_A2

# Print the result
print("Matrix Division:")
print(matrix_quotient)

Matrix Division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12.  Which function in Numpy can be used to swap the byte order of an array?

In NumPy, the function used to swap the byte order (endianess) of an array is numpy.ndarray.byteswap(). This function swaps the byte order of the array in place.

13.  What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to find the inverse of a square matrix. The inverse of a matrix is another matrix that, when multiplied with the original matrix, gives the identity matrix.

14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to rearrange the structure of an array, changing its dimensions while keeping the same data. It allows you to organize the elements in a different shape without altering the values, providing flexibility in representing and working with data in various formats.

np.reshape(array, new_shape)

15. What is broadcasting in Numpy?

Broadcasting in NumPy refers to the ability to perform element-wise operations on arrays with different shapes, allowing NumPy to implicitly adjust the dimensions for compatible operations. It eliminates the need for explicit looping or duplicating data, making array operations more concise and efficient. In broadcasting, smaller arrays are expanded to match the shape of larger arrays along compatible dimensions, facilitating seamless operations even when array shapes differ.

